name: Deploy Website

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML & CSS
        uses: anishathalye/proof-html@v2
        with:
          directory: "./"
          check_html: true
          check_css: false

      - name: HTML validacija ok
        if: ${{ success() }}
        run: echo "HTML validacija ok"

      - name: Deploy
        run: echo "Deploy done via GitHub Pages"
